name: Wolfboot Reusable Build Workflow

on:

  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config-file:
        required: true
        type: string
      make-args:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install cross compilers
        run: |
          sudo apt-get install -y gcc-arm-none-eabi gcc-aarch64-linux-gnu gcc-powerpc-linux-gnu gnu-efi

      - name: make clean
        run: |
          make keysclean && make -C tools/keytools clean && rm -f include/target.h

      - name: Install wolfSSL
        run: |
          sudo apt-get install --no-install-recommends -y -q make libwolfssl-dev

      - name: Select config
        run: |
          cp ${{inputs.config-file}} .config && make include/target.h

      - name: Build key tools
        run: |
          make -C tools/keytools

      - name: Test ed25519
        run: |
          ./tools/keytools/importTest.sh --ed25519
      - name: Test ed448
        run: |
          ./tools/keytools/importTest.sh --ed448
      - name: Test ecc256
        run: |
          ./tools/keytools/importTest.sh --ecc256
      - name: Test ecc384
        run: |
          ./tools/keytools/importTest.sh --ecc384
      # not supported yet
      #- name: Test ecc521
        #run: |
          #./tools/keytools/importTest.sh --ecc521
      - name: Test rsa2048
        run: |
          ./tools/keytools/importTest.sh --rsa2048
      - name: Test rsa3072
        run: |
          ./tools/keytools/importTest.sh --rsa3072
      - name: Test rsa4096
        run: |
          ./tools/keytools/importTest.sh --rsa4096
